name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: codeberg-tiny-lazy
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up Ruby environment
        uses: https://git.ryujinx.app/actions/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Build site
        run: bundle exec jekyll build
      - name: Publish site
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://${{ forge.event.repository.owner.username }}.codeberg.page/${{ forge.event.repository.name }}/
          token: ${{ forge.token }}
          source: _site/
