name: Deploy periodically

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * 0,5,6' # At 5:00am on Sunday, Friday, and Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages deployment
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
